import * as assets from './assets';
const Images = assets.Images;

export interface IBoardGame {
  name: string;
  img?: string;
  player?: [number] | [number, number] | [number, undefined];
  playTime?: [number] | [number, number];
  plus?: string[];
  isBuy?: boolean;
  order?: number;
}

export const data: IBoardGame[] = [
  {
    name: '모노폴리',
    img: Images.모노폴리,
    player: [2, 6],
    playTime: [60, 180],
    plus: ['k-확장판'],
    isBuy: true,
  },
  {
    name: '클루',
    img: Images.클루,
    player: [2, 6],
    playTime: [45],
    isBuy: true,
  },
  {
    name: '루미큐브',
    img: Images.루미큐브,
    player: [2, 4],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '스플렌더',
    img: Images.스플렌더,
    player: [2, 6],
    playTime: [30],
    plus: ['찬란한도시'],
    isBuy: true,
  },
  {
    name: '테라포밍마스',
    img: Images.테라포밍마스,
    player: [1, 5],
    playTime: [90, 120],
    plus: ['서곡', '비너스넥스트', '개척기지', '헬라스&엘리시움', '격동'],
    isBuy: true,
  },
  {
    name: '쿼리도',
    img: Images.쿼리도,
    player: [2, 4],
    playTime: [15],
    isBuy: true,
  },
  {
    name: '장난꾸러기 나방',
    img: Images.장난꾸러기나방,
    player: [3, 5],
    playTime: [15, 30],
    isBuy: true,
  },
  {
    name: '바퀴벌레 포커',
    img: Images.바퀴벌레포커,
    player: [2, 6],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '다빈치코드',
    img: Images.다빈치코드,
    player: [2, 4],
    playTime: [15],
    isBuy: true,
  },
  {
    name: '다빈치캐슬',
    img: Images.다빈치캐슬,
    player: [3, 6],
    playTime: [15],
    isBuy: true,
  },
  {
    name: '타르기',
    img: Images.타르기,
    player: [2],
    playTime: [60],
    isBuy: true,
  },
  {
    name: '뱅',
    img: Images.뱅,
    player: [4, 7],
    playTime: [20, 40],
    plus: ['확장판모음', '닷지시티', '골드러시'],
    isBuy: true,
  },
  {
    name: '퍼레이드',
    img: Images.퍼레이드,
    player: [2, 6],
    playTime: [45],
    isBuy: true,
  },
  {
    name: '컬러레또',
    img: Images.컬러레또,
    player: [2, 5],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '세트',
    img: Images.세트,
    player: [1, undefined],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '사보타지',
    img: Images.사보타지,
    player: [3, 10],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '위자드',
    img: Images.위자드,
    player: [3, 6],
    playTime: [45],
    isBuy: true,
  },
  {
    name: '달무티',
    img: Images.달무티,
    player: [4, 8],
    playTime: [15],
    isBuy: true,
  },
  {
    name: '보난자',
    img: Images.보난자,
    player: [3, 5],
    playTime: [45],
    isBuy: true,
  },
  {
    name: '로보77',
    img: Images.로보77,
    player: [2, 8],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '젝스님트',
    img: Images.젝스님트,
    player: [2, 10],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '참새작',
    img: Images.참새작,
    player: [2, 5],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '다이스 베이스볼',
    img: Images.다이스베이스볼,
    player: [2],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '카보',
    img: Images.카보,
    player: [2, 4],
    playTime: [45],
    isBuy: true,
  },
  { name: '쿠', img: Images.쿠, player: [2, 6], playTime: [15], isBuy: true },
  {
    name: '해저탐험',
    img: Images.해저탐험,
    player: [2, 6],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '타코 햇 케익 기프트 피자',
    img: Images.타코햇케익기프트피자,
    player: [2, 8],
    playTime: [15],
    isBuy: true,
  },
  {
    name: '엘리베이터앞에서',
    img: Images.엘리베이터앞에서,
    player: [2, 4],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '페이퍼사파리',
    img: Images.페이퍼사파리,
    player: [2, 5],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '해독제',
    img: Images.해독제,
    player: [2, 7],
    playTime: [20, 30],
    isBuy: true,
  },
  {
    name: '캘리코',
    img: Images.캘리코,
    player: [1, 4],
    playTime: [30, 45],
    isBuy: true,
  },
  {
    name: '티켓투라이드 미국',
    img: Images.티켓투라이드_미국,
    player: [2, 5],
    playTime: [30, 60],
    isBuy: true,
  },
  {
    name: '티켓투라이드 유럽',
    img: Images.티켓투라이드_유럽,
    player: [2, 5],
    playTime: [40, 60],
    isBuy: true,
  },
  {
    name: '초밥왕',
    img: Images.초밥왕,
    player: [2, 5],
    playTime: [10, 15],
    isBuy: true,
  },
  {
    name: '러브레터',
    img: Images.러브레터,
    player: [2, 4],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '도망자',
    img: Images.도망자,
    player: [2],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '번레이트',
    img: Images.번레이트,
    player: [2, 4],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '라스베가스',
    img: Images.라스베가스,
    player: [2, 5],
    playTime: [30],
    isBuy: true,
  },
  {
    name: '렉시오 플러스',
    img: Images.렉시오,
    player: [3, 5],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '노땡스',
    img: Images.노땡스,
    player: [3, 7],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '라마',
    img: Images.라마,
    player: [2, 6],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '달콤보',
    img: Images.달콤보,
    player: [2, 4],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '별빛 커피 은하수 다방',
    img: Images.별빛커피,
    player: [2, 4],
    playTime: [40],
    isBuy: true,
  },
  {
    name: '꼬치의달인',
    img: Images.꼬치의달인,
    player: [2, 4],
    playTime: [20],
    plus: ['그랜드마스터(~6인)'],
    isBuy: true,
  },
  {
    name: '센추리: 향신료의 길',
    img: Images.센추리,
    player: [2, 5],
    playTime: [30, 45],
    isBuy: true,
  },
  {
    name: '달빛 아래에서 수를',
    img: Images.달빛아래에서수를,
    player: [2],
    playTime: [20],
    isBuy: true,
  },
  {
    name: '스파이폴2',
    img: Images.스파이폴2,
    player: [3, 12],
    playTime: [15],
    isBuy: true,
  },
  {
    name: '요트다이스',
    img: Images.요트다이스,
    player: [1, undefined],
    playTime: [30],
    isBuy: true,
  },
  { name: '티츄', img: Images.티츄, player: [4], playTime: [60], isBuy: false },
  {
    name: '마법사의레시피',
    img: Images.마법사의레시피,
    player: [2, 4],
    playTime: [30],
    isBuy: false,
  },
  {
    name: '크라스 카리어트',
    img: Images.크라스카리어트,
    player: [3, 5],
    playTime: [30],
    isBuy: false,
  },
  {
    name: '서펜티나',
    img: Images.서펜티나,
    player: [2, 4],
    playTime: [15],
    isBuy: false,
  },
  {
    name: '카탄',
    img: Images.카탄,
    player: [3, 4],
    playTime: [75],
    isBuy: false,
  },
];
